version: '3'

services:
  hyperscaler_test_cloud_dev:
    container_name: hyperscaler_test_cloud_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d
    volumes: 
      - .:/extension
    env_file:
      - .hyperscaler_test_cloud_dev.env

  hyperscaler_test_cloud_bash:
    container_name: hyperscaler_test_cloud_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .hyperscaler_test_cloud_dev.env

  hyperscaler_test_cloud_test:
    container_name: hyperscaler_test_cloud_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
    env_file:
      - .hyperscaler_test_cloud_dev.env
